#!/bin/sh

voltage=$1

echo	"&MAIN														"
echo	"*Reduce the drift voltage to 250 V/cm                                                                          "
echo	"&CELL                                                                                                          "
echo	"cell-id "Aligned Grid"                                                                                         "
echo	"                                                                                                               "
echo	"plane y=20.4 v=-10151 label p1                                                                                 "
echo	"*plane y=20.4 v=-5075.5 label p1                                                                               "
echo	"plane y=-0.471 v=0 label p2                                                                                    "
echo	"                                                                                                               "
echo	"* Syntax:                                                                                                      "
echo	"* rows                                                                                                         "
echo	"* <identifier> <number_of_wires> <diameter> <x_coord> <y_coord> [<Vbias> [<weight> [<length> [<density>]]]]    "
echo	"*                                                                                                              "
echo	"ROWS                                                                                                           "
echo	"*use the same wire pitch for plane and wires                                                                   "
echo	"y1 40 .015 -23.55+i*0.471 	0.0 	${voltage}	                                                        "
echo	"d1 21  .015 -4.71+i*0.471     	0.0     ${voltage}                                                              "
echo	"y2 40 .015 5.181+i*0.471 	0.0 	${voltage}                                                              "
echo	"v1 40 .015 -23.55+i*0.471  	0.471 	0                                                                       "
echo	"l1 21  .015 -4.71+i*0.471      	0.471   0                                                               "
echo	"v2 40 .015 5.181+i*0.471  	0.471 	0                                                                       "
echo	"u1 40 .015 -23.55+i*0.471 	0.942   -370	                                                                "
echo	"s1 21  .015 -4.71+i*0.471  	0.942   -370                                                                    "
echo	"u2 40 .015 5.181+i*0.471 	0.942   -370	                                                                "
echo	"g1 40 .015 -23.55+i*0.471       1.413   -665                                                                   "
echo	"k 21 .015 -4.71+i*0.471        1.413    -665                                                                   "
echo	"g2 40 .015 5.181+i*0.471       1.413    -665                                                                   "
echo	"                                                                                                               "
echo	"*duplicate definition of x need to manually strip the data file                                                "
echo	"*&field                                                                                                        "
echo	"*area -15 -3 15 20                                                                                             "
echo	"*plot-field cont vector surf hist                                                                              "
echo	"*                                                                                                              "
echo	"*area -.2 .2 0 .4                                                                                              "
echo	"*plot cont n 40                                                                                                "
echo	"*                                                                                                              "
echo	"*area 0 .5 .2 .7                                                                                               "
echo	"*plot cont n 40                                                                                                "


